apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-9ctq61
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-9ctq61
  namespace: my-nginx-9ctq61
  labels:
    name: nginx-9ctq61
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-9ctq61
  template:
    metadata:
      namespace: my-nginx-9ctq61
      labels:
        name: nginx-9ctq61
    spec:
      containers:
      - name: nginx-9ctq61
        image: nginx
        ports:
        - containerPort: 80

