apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-app-1mldwx43
  namespace: wego-system
resources:
- app.yaml
- test-app-1mldwx43-gitops-deploy.yaml
- test-app-1mldwx43-gitops-source.yaml
